### ISSUE TITLE
Mapa de procesos

### ISSUE THREAD

**Issue by OlimpiaGarcia** [Black-Dot-2024/docs#10]
## Tasks
- [ ] Creación de la pagina en la wiki de procesos
- [x] Planeación
- [x] Requisitos
- [x] Calidad
- [x] Retroalimentación
- [x] Desarrollo

## Extra

**Comment by alejandraa-cruiz** [comment]
Ir mapeando los procesos existentes

**Comment by UriGOPAR** [comment]
Link para el draw .io

https://drive.google.com/file/d/1gMCt5ICeuNrQZRTbwLZbVu27HcoR0h3U/view?usp=sharing

**Comment by alejandraa-cruiz** [comment]
Holaa la verdad estoy medio trabada ahorita con visualizar los procesos y ver qué nos falta y así ¿alguien de los asignados tendrá tiempo de darme un overview de cómo va el mapa 😭 graciasss
