### ISSUE TITLE
SCAMPI - RSKM

### ISSUE THREAD

**Issue by danfupo03** [Black-Dot-2024/docs#103]
## Descripción
Existen 3 Specific Goals. Les adjunto las tasks de cada Specific Goal:

## Task
- [ ] SG 1.1
- [ ] SG 1.2
- [ ] SG 1.3
- [ ] SG 2.1
- [ ] SG 2.2
- [ ] SG 3.1

## Extras
> [!NOTE]
> Si no estoy equivocado, lo más que podemos aspirar en este SCAMPI es:
> SG 1 (verde)
> SG 2 (verde)
> SG 3 (rojo)

**Comment by JP-coder2000** [comment]
Lo hice ayer, queda sujeto a revisión de @yna2131 y @sgarnica1
