### ISSUE TITLE
Crear mapa de sitio/flujo de CR

### ISSUE THREAD

**Issue by DamarizLicea** [Black-Dot-2024/docs#104]
## Descripción
Crearlo para presentar

## Task
- [x] Hacerlo en pizarron
- [x] Pasarlo a figma 

## Extras
-

**Comment by JP-coder2000** [comment]
Link: https://docs.google.com/drawings/d/1QXai6SgRRIUaAwgacnpRjFo13z06GW1kIH9VMumS2bY/edit?usp=sharing
