### ISSUE TITLE
Levantamiento de Requisitos ZG

### ISSUE THREAD

**Issue by OlimpiaGarcia** [Black-Dot-2024/docs#12]
# Descripción
Hacer el levantamiento de requisitos de la OSF

# Tasks
- [x] Proceso de levantamiento de requisitos
- [x] Documentar requisitos en wiki

## Extras
El miércoles a la 1pm nos vamos a juntar para definir los requisitos

**Comment by alejandraa-cruiz** [comment]
el proceso tuvo cambios revisen la versión 1.1.0

**Comment by DHurtado714-itesm** [comment]
Ya se creo el doc y ya empece a llenarlo

https://docs.google.com/document/d/1j7CtRqzuAebw2_GAww44feldwdizBmAH_09C2hNYo3M/edit#heading=h.fiuigjb6owua
