### ISSUE TITLE
Presentación "Reinventando las Organizaciones" 

### ISSUE THREAD

**Issue by danfupo03** [Black-Dot-2024/docs#13]

**Comment by danfupo03** [comment]
@DavidLangarica Podrías poner el link de tu presentación aquí por favor 👍

**Comment by DavidLangarica** [comment]
Link a la presentación: https://www.canva.com/design/DAF9LpLCJ4g/4nBsAi0hrZ0p2lh8itIUCA/edit?utm_content=DAF9LpLCJ4g&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton
