### ISSUE TITLE
Levantamiento de Requisitos CR

### ISSUE THREAD

**Issue by OlimpiaGarcia** [Black-Dot-2024/docs#14]
# Descripción
Hacer el levantamiento de requisitos de la OSF

# Tasks
- [ ] Proceso de levantamiento de requisitos
- [ ] Documentar requisitos en wiki

**Comment by alejandraa-cruiz** [comment]
el proceso tuvo cambios revisen la versión 1.1.0

**Comment by dvegaa20** [comment]
SRS: https://docs.google.com/document/d/1hI8OAU9Ew45tZoit4cKFguI77ariTvotBL8Udo071mU/edit
