### ISSUE TITLE
ZG - Spike de notificaciones

### ISSUE THREAD

**Issue by DHurtado714-itesm** [Black-Dot-2024/docs#145]

**Comment by sgarnica1** [comment]
**Documentación del Spike**
https://docs.google.com/document/d/1haHBVrZwpU9ywZ6pp4BXD9j35C9okK7SziSfF9onktU/edit#heading=h.1tam2acff67m

**Repo**
- https://github.com/sgarnica1/websocket-test
- https://github.com/DenisseDB/notificacion_socket.git

**Comment by sgarnica1** [comment]
https://github.com/Black-Dot-2024/docs/assets/71858836/cf38b936-586c-4f3b-a464-05ff82f0d116
