### ISSUE TITLE
Definición de Ready y Done

### ISSUE THREAD

**Issue by sebFlores02** [Black-Dot-2024/docs#159]
# Descripcion

Establecer la definición de de Ready y Done en relacion a las US.

**Comment by lCDSLl-Richard** [comment]
De esto hay otra issue en la que está @DanielSebasCM que es departamental, usaremos dos definiciones?

**Comment by DanielSebasCM** [comment]
Yo hice el Issue pero lo esta haciendo Charlie. Tengo entendido que si vamos a usar dos porque las definiciones de CR van a ir cambiando con el tiempo
