### ISSUE TITLE
Visión del proyecto ZG

### ISSUE THREAD

**Issue by OlimpiaGarcia** [Black-Dot-2024/docs#17]
# Descripción
Definir la visión del proyecto, de acuerdo al [proceso](https://github.com/Black-Dot-2024/docs/wiki/PRO%E2%80%90BDT%E2%80%90005-Definir-visi%C3%B3n-del-proyecto).

## Tareas
- [x] Creación de la página en la wiki de GH
- [x] Objetivo
- [x] Alcance
- [x] Criterios de éxito
- [x] Hitos del proyecto
- [x] Número de iteraciones
- [x] Riesgos
- [x] Método de estimación de las tareas

## Extra

> [!NOTE] 
> Revisar diapositiva de visión de proyecto de DAD

**Comment by lCDSLl-Richard** [comment]
## Fecha de entrega
28/02 al final del día

## Tareas asignadas
@salgue441 Pasar el documento de project charter a página de wiki
@yna2131 trabajando en riesgos
@ArmandoRosasB e @Ian326 trabajando en la definición del numero de iteraciones del plan de vida del proyecto
@RodrigoTeran trabajando en el método de estimaciones
