### ISSUE TITLE
WBS Departamental

### ISSUE THREAD

**Issue by danfupo03** [Black-Dot-2024/docs#19]
# Descripción
Generar un WBS con las siguientes especificaciones:

## Inicio:
- [x] Plan de proyecto
- [x] Definición de la forma de trabajo

## Ejecución:
- [x] WBS genérico de los requisitos

## Cierre:
- [x] Solución de software
- [x] Manuales de usuario
- [x] Manuales de entrenamiento
- [x] Manuales de operaciones
- [x] Manuales de apoyo
- [x] Overview del sistema

## Extras
- Revisar las presentaciones de Lalo
- Checa de jedi el wbs  como guía

**Comment by alejandraa-cruiz** [comment]
Dato importante: FALTA PROCESO DE PLANEACIÓN DE PROYECTO :)

**Comment by danfupo03** [comment]
Los que están trabajando en el WBS:

Lalo nos comentó que vean el WBS del Departamento Jedi, que está muy bien hecho y les puede dar una idea de cómo se debe de hacer.

**Comment by OlimpiaGarcia** [comment]
¿Cómo van??

**Comment by ArmandoRosasB** [comment]
Falta que alguien lo revise y nos de retro

**Comment by OlimpiaGarcia** [comment]
> Falta que alguien lo revise y nos de retro
pueden subir el link aquí para que lo podamos checar?? pls

**Comment by DiegoPerdomoS** [comment]
https://miro.com/app/board/uXjVNseGA4o=/
