### ISSUE TITLE
WBS Requisitos

### ISSUE THREAD

**Issue by danfupo03** [Black-Dot-2024/docs#20]
# Descripción
Es la parte de ejecución, cómo se desarrolla un requisito en sus tres fases

## Inicio:
- [x]  Scope
- [x] Research 
- [x] Synthesis
## Ejecución:
- [x] Ideation
- [x] Validation
- [x] Development
- [x] Testing
## Cierre
- [x] Transición
- [x] Análisis de resultados

## Extras
- Investigar los procesos y aterrizar más este Issue
- Validar congruencia con procesos

**Comment by alejandraa-cruiz** [comment]
Este wbs es parte del proceso de levantamiento y entendimiento de requerimientos es la actividad uno de la fase de definición. Se levanta solamente un wbs de todo el proceso de trabajo detrás de un requerimiento desde que se idea hasta que se implanta, y todo lo que esto conlleva :) Chequen el proceso es el 004, va después del 005 (visión del proyecto)

**Comment by dvegaa20** [comment]
Miro: https://miro.com/app/board/uXjVNseGA4o=/

**Comment by lCDSLl-Richard** [comment]
## Actualización

Última revisión por @JP-coder2000

**Comment by JP-coder2000** [comment]
Aprobado, voy a mover el issue a done.
