### ISSUE TITLE
CR-Documento de requisitos apegado a estándares internacionales

### ISSUE THREAD

**Issue by danfupo03** [Black-Dot-2024/docs#27]
## Descripción
Requisitos funcionales y no funcionales

## Tasks
- [x] Checar proceso de requisitos
## Extra

- chequen lo que claud nos dio de ingenieria de requisitos

**Comment by CharlesVela66** [comment]
https://docs.google.com/document/d/1hI8OAU9Ew45tZoit4cKFguI77ariTvotBL8Udo071mU/edit?usp=sharing
