### ISSUE TITLE
Estrategia de comunicacion CR

### ISSUE THREAD

**Issue by OlimpiaGarcia** [Black-Dot-2024/docs#35]
Como nos vamos a comunicar con el socio?

- [x] Llenar la wiki de comunicacion de CR
- [x] Incluir forma de comunicación: correos, juntas,etc

**Comment by Bromaeg** [comment]
Actualice la wiki de comunicación, inclui la plantilla formal, favor de validarlo.
¡Gracias!.

**Comment by OlimpiaGarcia** [comment]
listo, gracias Mike
