### ISSUE TITLE
Estrategia de comunicacion ZG

### ISSUE THREAD

**Issue by OlimpiaGarcia** [Black-Dot-2024/docs#36]
Como nos vamos a comunicar con el socio?

- [x] Llenar la wiki de comunicacion de ZG
- [x] Incluir forma de comunicación: correos, juntas,etc

**Comment by DenisseDB** [comment]
Ya está en la wiki nueva

**Comment by OlimpiaGarcia** [comment]
> Ya está en la wiki nueva

me sale que el link esta roto

**Comment by FridaBG** [comment]
Yo lo veo bien, pasaré la issue a done. Gracias Denisse :)
