### ISSUE TITLE
Definir misión y visión 

### ISSUE THREAD

**Issue by OlimpiaGarcia** [Black-Dot-2024/docs#4]
- [x] Ideas de misión y visión
- [x] Construcción de misión y visión
- [x] Validación de misión y visión
- [x]  Pasar doc a Github

**Comment by FridaBG** [comment]
Aquí están ya la misión, visión y valores en el git: https://github.com/Black-Dot-2024/docs/wiki/Misi%C3%B3n,-Visi%C3%B3n,-Valores-y-Objetivos:
