### ISSUE TITLE
Stack CR

### ISSUE THREAD

**Issue by OlimpiaGarcia** [Black-Dot-2024/docs#7]
## Descripción 
Se realiza la  elección del stack 

## Tasks
- [x] Definir stack
- [x] Crear una hoja de la wiki de stack
- [x] Pasar tu stack a la hoja de la wiki

## Extra

**Comment by OlimpiaGarcia** [comment]
no esta en la wiki

**Comment by Riosmena** [comment]
# Diagrama de Despliegue

[Diagrama de Despliegue CR Organizacional](https://viewer.diagrams.net/?tags=%7B%7D&highlight=0000ff&edit=_blank&layers=1&nav=1&title=Diagrama%20de%20despliegue%20CR.drawio#R7VvbcuI4EP0aHkPZli%2FwyCXJTFVSywRmZ2tfphRbgGdtNyuLkOTrV7LlqxwgGRxYiiestixLffp0t1uig0bh8y3Fq%2BU9eCToGJr33EHjjmHomqXxHyF5SSWW1UsFC%2Bp7slMhmPqvJHtSSte%2BR%2BJKRwYQMH9VFboQRcRlFRmmFDbVbnMIqm9d4QVRBFMXB6r0h%2B%2BxZSrtZcsS8i%2FEXyyzN%2BuavBPirLMUxEvswaYkQtcdNKIALL0Kn0ckEMrL9JI%2Bd%2FPG3XxilERsnwd%2B%2Fm2Zw8d%2F%2F%2FoO018O%2FPj29PBzdmWkozzhYC0X%2FIWw14hQLhwTz3cxIx6%2FnhL6JITJQthLph0uY7xPMAj8RcRFDFYdNMSyFZA5n9kwXmHXjxYzcW%2FcKwR3ye2xUUgepCL1RLbEK%2FEad%2F1IRDM1DW4XaOj5lGPtg3hJDGuh6OEcIjaVMzN5e8nCQPTnl5ulz8iUv0Lc23A75TJVe1KhYknkuSSS2rwlEBJGX3gXeZdbQfqING2jL5HeFIZim7LPsmwkWmYkWFrnIh%2B8AJBfSAzfgaep4DmCMFxHPhMTBw%2BA%2F%2FzZ1Z0LlGUoUeZuMi9lq1DmsjKUdr8tJC1TgYh43DXJJlC2hAVEOLgupEMK68gjYlih26LPHSSICQ3%2BIoy9SD%2BL1wyq%2BiWRNxBekzcjiEgqufHF1JMh39Q1x466ZJunkYpimC4I29JRmqZY7FboKAkw85%2BqfroJhuRRvir8UuqwAj9icWnkiRAUFmE5VYtwUM27vq8%2Fv0hnUBhEvpSP20im0xLdJcXdEutD8NYBiS%2BMLzPerjE%2Bd9Qlxuehu8z4PDM5OOP1M2O8tSfhdXQSjNeNmknomvkJHDb7ago2m02mjbZwhx95fl3BL%2BOry%2FHhGRoa1mkd%2Bp6XmgrhNMSPyXgCWakQPrg17FjjRqy3GqrCtjwNl2%2BpZLpNLLzSusjpORW1X8mh3oe2AueVYVbRrA4A83nMrbLO2QMAail4dgwbh8JvBcKjDiZfc8GCJVrXvg4u3rlsF7puVLnYb8it9V6De84fPLh7tnfgOh4qsE4gZgtKpt%2Fu0qzbvqC8LetGDVm3YTaBbLUFcv8YITjmIZLVgnAiK4Xh9sK0s2eYtk8iSpu1PNvWtuflO%2Fq3E9P1jAqFr5iNJicc0bMc5LcDutY1LUdvJZ5XR7U%2BLZ47CpZ%2FPNxfHHnFkZs1kh0%2FWmf2cS4fU709vfSJfEzZNbfb31E%2B2dG%2FHTfdU5h9Ha4CeCGXYkmtWIJqxS1NLZY00dtujd3GebFbN%2F5f9HbqdLW203tH%2F5ayMEPh95S4a5pURS%2F0LqFTp7e1H72d1uiNzozeaE96n%2BbeR70Qunvzw%2FkMeiOF3jMccGzyMsKF383hu987enpuntleh94%2FFsN%2Fb8tJ3Xy4T3YLuWz0cGHRto%2FcvnN0FhnqXkO321Vg4wtkTXWlsg71bXWmKoJIRTARMQr%2FkBEEQAt%2BUWCYvVmhGnLFjLSuJWpVxoi39aKdlK9WnOQjiPjQ2E%2BAIzhmGxKzKuKH8JG1ENYz9suBDLutHMg6Lw%2BJ9s2BUP%2BkXCRS04zavg958vnKlb2f0cV9Vrf0av7TbCgSNlOstRMX5pmVEdC%2BVULz0BT70HdGvqmblY317Z8ZO%2Fq3dD5D5f%2Bpn8%2FIzPog5zO0vo0qWr%2BSzY%2Fu57S%2FY4PUwm7VZQ%2FFuXBxnLnms28BFmnuu6R8FiInMbR7eOXcxPzqhjvSOTxLse9SiGEuliTcQyodrFbJAFM8x9S%2FRIBqBKgdmLaso2fQSP0A%2Bh6vOXSgYJfpdx0GA5dBmcoJ7ScQ%2B1LHj8AYhA1cT%2FE%2BbOaq5weT88PLauqKGrT6geo8bxZ%2FWEjpWvztA13%2FBw%3D%3D)

**Comment by Riosmena** [comment]
# Diagrama de Paquetes

[Diagrama de Paquetes CR Organizacional](https://viewer.diagrams.net/?tags=%7B%7D&highlight=0000ff&edit=_blank&layers=1&nav=1&title=Diagrama%20de%20paquetes%20CR.drawio#R7VxNk5s4EP01PoYChPg4jifZTKqyu6mdQzZHYWRbFYEckMf2%2FPoVRnyKjDFT3sKAL4aWkOR%2B73VDo5kFeAyPn2O02%2F7JAkwXph4cF%2BDjwjQNHeriK7WcMguEbmbYxCSQnUrDM3nF%2BZXSuicBTmodOWOUk13duGJRhFe8ZkNxzA71bmtG67Pu0AYrhucVoqr1Own4NrO6plPanzDZbPOZDdvLWkKUd5a%2FJNmigB0qJvBpAR5jxnh2FB4fMU2dl%2Fslu%2B6P37QWC4txxLtcsPzu%2FfvP3z9eT0%2Foy36X%2BB%2F%2F%2BsU%2BSDBeEN3LHywXy0%2B5B8S6d%2Blh6jocL8ByzSL%2BLNsNcc6Rn7vGELCdDYVPgDR8YwnhhEXCRPFatCy3PKRyBJ%2FtowAHX%2F3cQJGP6ZfoCaPzlGebQJgjElXOKUW7hPjnhaTTHLaE4%2BcdWqWGg%2BCjsKleko57wTHHx4pJeu0zZiHm8Ul0ka2WRFQy2JN4Hip0sOWg2woVnBx4JCm4KUYuURIHEqgrQPMug1ZxbsJj9hM%2FMspSz0UsEl2WMU6E1ArYCkuBW2paE0ob1wlH8hKPVHGo9D%2BilB0ectGlFhENcLVHN4TeZOpl2GrA6JpX%2FagwQR3Uu1hZnxhTxMlLPQy0QSkX8I0Rsf6CJaABPluvE8wV6Itl92dDHilHS4erBQvrgjWAqlgHXiQGAPaN9GsYCmIoCFiUzLG3CaWj16GEKpSWrqvg2TcLvoY5crm9Tdmrwi9wW6CxwN1FWKhAHrJgL%2Fw6dr2%2BlwvFY0BNxdDSTBsY0HE9ywG2CxVNtxIH6lDLL7HEmDcLz%2FYkFQ47o1oFyvEu5lEBtw5LwO9N%2Faaq%2FlResZAUjsefst9LFtlq1kOAZWk5ESpsKtJ7lT%2BGCUW4uJHWzUlq3eyldcPyWp%2BUqmC5jma7hhIP7kfsjsKHAIdsVnlHlRsDlXmHOtcIZe50xm9iMgeqzMO0dD2n837p3PB0IV69%2FJgDED2YpOjBLPrfeUatmyd4tY8JP82y75ffB6l7a%2BwF8bfZPeu%2ByQe13P5C8GHO9f1yPRjKTb01yUq81asSPwmdA4UPB%2FKK4mAWer%2FsPhylW5NUOugM4NSUrpbkF6ZNuVRySox8I5n9a59usFoa5WGNN6WxcrSR3%2BcR%2Fdb%2B6TwfslkeRAdb3x1bR9E0LR9I%2FFS%2FObiwZSvOzQ1WC%2BAbgQVRsklDzkqQ5xy7UnqQFaIPsiEkQZBe3kq9OAtLkpyZUHJNeFfElutfATbe5EPH0HT1xZ%2FdFlpu9ipfTRhJvBp9tuixAe7yLgzg%2FL%2B7MCaZEYxeGQGYtmY5OnRdE0DTy28g73tPhqW%2BuOPH0Uv3vazIW2FNzzas78cYRBFHrdBPQOAFq%2BdbvqZn1GJ%2BgH2ColnzXas4dyD6Se5st3ptbZ%2BC6KFayQ%2FY%2BG%2FQb5PlxXOU5rgVxdsDUDxUa%2FMTUHzB61nxTc%2BoNX0WsKnuv3p3kh%2Bm5tWyyxQ0b3YGc2qaV2s5Yqb9bhZ9rzwPGnf23hAk31awH7%2Fkrc5Qjkby4rT8k%2Fase%2FmPAcCn%2FwA%3D)
