### ISSUE TITLE
Enviar invitaciones para presentación final

### ISSUE THREAD

**Issue by danfupo03** [Black-Dot-2024/docs#72]
## Task
- [x] Crear invitación
- [x] Enviar a profes
- [x] Enviar a socios
- [x] Enviar a directivos
- [x] Enviar a nosotros
- [x] Enviar a AIRA
- [ ] PD: Enviar a padre de familia

## Extras
> [!NOTE]
> Profes: Los 10 del curso, [Óscar  Hernández](ohernand@tec.mx), [Pedro Pérez](pperezm@tec.mx) y [Benjamín Valdés](bvaldesa@tec.mx)
> Directivos: Ricardo Cortés, Agustín Domínguez

**Comment by RodrigoTeran** [comment]
La invitación ya está:

[Invitación Presentación BlackDot.pdf](https://github.com/Black-Dot-2024/docs/files/14515537/Invitacion.Presentacion.BlackDot.pdf)
