### ISSUE TITLE
Stack ZG

### ISSUE THREAD

**Issue by OlimpiaGarcia** [Black-Dot-2024/docs#8]

**Comment by salgue441** [comment]
# Stack de ZeitGeist 🚀

## Tecnologías 🖥️

### Frontend 🌐

- [**React**](https://reactjs.org/) ⚛️: Biblioteca de JavaScript para construir interfaces de usuario. Utilizada para gestionar el estado y las interacciones en la aplicación web.
- [**TypeScript**](https://www.typescriptlang.org/) 📘: Superset de JavaScript que añade tipado estático, mejorando la calidad del código y la productividad.
- [**Tailwind CSS**](https://tailwindcss.com/) 🎨: Framework de CSS para diseñar componentes de interfaz de usuario con estilos predefinidos y utilidades personalizables.

### Backend 🔧

- [**Node.js**](https://nodejs.org/) 🟢: Entorno de ejecución para JavaScript en el servidor, maneja las solicitudes HTTP y la lógica de negocio.
- [**Express.js**](https://expressjs.com/) 🚀: Framework para Node.js que facilita la creación de servidores web y la definición de rutas de API.
- [**Prisma**](https://www.prisma.io/) 🗃️: Herramienta ORM para modelar y gestionar la base de datos, simplificando las interacciones con PostgreSQL.
- [**PostgreSQL**](https://www.postgresql.org/) 🐘: Sistema de gestión de bases de datos relacional, utilizado para almacenar los datos de la aplicación.
- [**Mocha**](https://mochajs.org/) & [**Chai**](https://www.chaijs.com/) ☕🍵: Herramientas para realizar pruebas unitarias y de integración en el backend.
